# センサーインスタンスの一覧を見る
GET http://localhost:8080/api/v1/sensor
Content-Type: application/json

### TODO: センサーインスタンスを登録する
POST http://localhost:8080/api/v1/sensor
Content-Type: application/json

### TODO: ある1つのセンサーインスタンスのデータを見る
## 必要な情報: インスタンスID、値
GET http://localhost:8080/api/v1/sensor/2
Content-Type: application/json

### TODO: センサー値をサーバーへ送信する
PUT http://localhost:8080/api/v1/sensor/2/23
Content-Type: application/json

### TODO: センサー値をサーバーへ送信する
PUT http://localhost:8080/api/v1/sensor/1/122

### TODO: すべてのデータを見る
GET http://localhost:8080/api/v1






# ### Get Books by ID
# GET http://localhost:8080/api/v1/books/1

# ### Create Book
# POST http://localhost:8080/api/v1/books
# Content-Type: application/json

# ### Update Book By Id
# PUT http://localhost:8080/api/v1/books/1
# Content-Type: application/json

# ### Delete Book By ID
# DELETE http://localhost:8080/api/v1/books/1