### Get Sensor Instance list
GET http://localhost:8080/api/v1/sensor
Content-Type: application/json

### Create Sensor Instance
POST http://localhost:8080/api/v1/sensor
Content-Type: application/json

### Set application/json Value by ID
PUT http://localhost:8080/api/v1/sensor/1/123
Content-Type: application/json

{"id": 1, "value": 123}

### Get text/plain Value by ID
GET http://localhost:8080/api/v1/sensor/1
Content-Type: application/json

### Get text/plain Value all
GET http://localhost:8080/api/v1





### Get Books by ID
GET http://localhost:8080/api/v1/books/1

### Create Book
POST http://localhost:8080/api/v1/books
Content-Type: application/json

### Update Book By Id
PUT http://localhost:8080/api/v1/books/1
Content-Type: application/json

### Delete Book By ID
DELETE http://localhost:8080/api/v1/books/1