### echo Hello World!
GET http://localhost:8080

### Get Books by ID
POST http://localhost:8080/api/v1/sensor

### Get Books by ID
PUT http://localhost:8080/api/v1/sensor/aaa/222?aaa=2

### Get Books by ID
GET http://localhost:8080/api/v1/books/1

### Create Book
POST http://localhost:8080/api/v1/books
Content-Type: application/json

### Update Book By Id
PUT http://localhost:8080/api/v1/books/1
Content-Type: application/json

### Delete Book By ID
DELETE http://localhost:8080/api/v1/books/1